version: '3'

services: 
  mysql_wordpress:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wp_dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_wordpress
      MYSQL_ROOT_PASSWORD: root

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql_wordpress
    ports:
          - 8080:80
    environment:
          WORDPRESS_DB_HOST: mysql_wordpress
          WORDPRESS_DB_USER: wp_dwes
          WORDPRESS_DB_PASSWORD: dwes
          WORDPRESS_DB_NAME: wordpress
