# Versión utilizada
version: '3'

# Configuración de los servidores que vamos a necesitar
services: 
 
  # mysql es el nombre que vamos a dar a este primer servicio
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build: mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: dwes

  apache:
    build: apache/
    ports:
      - 8080:80
    volumes:
      - proyecto:/var/www/html/

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  
  mysql_wordpress:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql_wordpress
    ports:
          - 8082:80
    environment:
          WORDPRESS_DB_HOST: mysql_wordpress
          WORDPRESS_DB_USER: dwes
          WORDPRESS_DB_PASSWORD: dwes
          WORDPRESS_DB_NAME: wordpress


volumes: 
  proyecto:
